import { pool } from "./index";

async function run() {
  try {
    console.log("Wiping static/seeded data...");
    
    // The seeded events have acq_date = '2026-08-28' or similar. 
    // Wait, the seed script had these hardcoded facilities:
    // 'Bokaro Steel Plant (SAIL)', 'Jamnagar Refinery Complex (Reliance)', etc.
    
    // 1. Delete alerts generated by the seeded events
    await pool.query(`
      DELETE FROM alerts 
      WHERE classified_event_id IN (
        SELECT id FROM classified_events 
        WHERE hotspot_id IN (
          SELECT id FROM hotspots WHERE acq_date = '2026-08-28'
        )
      )
    `);
    
    // 2. Delete classified events linked to seeded hotspots
    await pool.query(`
      DELETE FROM classified_events 
      WHERE hotspot_id IN (
        SELECT id FROM hotspots WHERE acq_date = '2026-08-28'
      )
    `);

    // 3. Delete seeded hotspots
    const res = await pool.query(`
      DELETE FROM hotspots WHERE acq_date = '2026-08-28' RETURNING id
    `);
    
    console.log(`Deleted ${res.rowCount} static/seeded hotspots and their alerts/events.`);

    // 4. Also wipe the simulated Alert sent manually in seed.ts which might have been missed if it had no acq_date
    // Wait, the alert in seed.ts was mapped directly to the event inserted, which is linked to the hotspot with '2026-08-28'.
    // So the above takes care of it.
    
  } catch (err) {
    console.error("Error wiping data:", err);
  } finally {
    await pool.end();
  }
}

run();
